# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Ora Maritima
email: oramaritima@brandt.id.au
description: A collection of materials to support Ora Maritima A Latin Story for Beginners with Grammar and Exercises by E. A. Sonnenschein, D.Litt., Oxon.
baseurl: "/oramaritima"
url: ""
rooturl: "http://www.brandt.id.au"
twitter_username: veromarybrrr
github_username:  veromary

# Build settings
markdown: kramdown
google_analytics: UA-39801667-1

